<!DOCTYPE html>
<html>
<head>
    <style>
        body { font-family: Arial, sans-serif; }
        .report-section { margin-bottom: 30px; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #f5f5f5; }
        h1 { color: #333; }
        .header { margin-bottom: 20px; }
        .footer { margin-top: 30px; font-size: 12px; color: #666; }
    </style>
</head>
<body>
    <div class="header">
    <h1>Library Management System - Reports</h1>
    <div class="meta-info">Generated on: <?= $currentDateTime ?></div>
    <div class="meta-info">Generated by: <?= $currentUser ?></div>
</div>

<div class="report-section">
    <h2>Books by Type</h2>
    <table>
        <thead>
            <tr>
                <th>Book Type</th>
                <th>Count</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($bookTypes as $index => $type): ?>
            <tr>
                <td><?= h($type) ?></td>
                <td><?= h($bookCounts[$index]) ?></td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="report-section">
    <h2>Monthly Issues</h2>
    <table>
        <thead>
            <tr>
                <th>Month</th>
                <th>Number of Issues</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($months as $index => $month): ?>
            <tr>
                <td><?= h($month) ?></td>
                <td><?= h($totals[$index]) ?></td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="report-section">
    <h2>Return Status Distribution</h2>
    <table>
        <thead>
            <tr>
                <th>Status</th>
                <th>Count</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($statuses as $index => $status): ?>
            <tr>
                <td><?= h($status) ?></td>
                <td><?= h($statusCounts[$index]) ?></td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="footer">
    <p>This report was automatically generated from the Library Management System.</p>
    <p>© <?= date('Y') ?> Library Management System. All rights reserved.</p>
</div>
</body>
</html>